# Generated by Django 2.1.4 on 2019-02-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timeline',
            field=models.ImageField(default='timeline.jpg', upload_to='timeline'),
        ),
    ]
