# Generated by Django 2.1.4 on 2019-02-20 09:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20190219_1446'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('draft', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
