# Generated by Django 2.1.4 on 2019-02-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_auto_20190222_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='collage'),
        ),
    ]
